### PR TITLE
Fix Windows Builds

### PR DESCRIPTION
**Pull request by wfondrie**
This PR adds the Thermo MSFileReader installation to our Windows build. Currently it is a draft while I figure it out.

### CODE REVIEW

**Comment by mammmals** [comment]
Looks like a new certificate issue. Thoughts @wfondrie?

**Comment by wfondrie** [comment]
I was just about to ask you and @jke000. Unfortunately I don't have much experience with building things with Visual Studio.

Here are the two errors I'm seeing:
```
   C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3326,5): error MSB3326: Cannot import the following key file: . The key file may be password protected. To correct this, try to import the certificate again or import the certificate manually into the current user’s personal certificate store. [D:\a\Comet\Comet\CometUI\CometUI.csproj]
```
```
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3326,5): error MSB3321: Importing key file "CometUI.pfx" was canceled. [D:\a\Comet\Comet\CometUI\CometUI.csproj]
```

Any suggestions you have would be great!

**Comment by mammmals** [comment]
Hmm, looks like it's only an issue for the CometUI. We could potentially just ignore that in the MSBuild and only build the exe for now?

**Comment by wfondrie** [comment]
Maybe - I'll see if I can configure it that way 🤔

**Comment by mammmals** [comment]
Another option: https://manfredlange.blogspot.com/2008/03/visual-studio-unable-to-find-manifest.html

**Comment by mammmals** [comment]
Looks like the certificates are line 79-92 in https://github.com/UWPR/Comet/blob/master/CometUI/CometUI.csproj
Not sure if this would have other issues though...

**Comment by mhoopmann** [comment]
Try disabling the ClickOnce security setting in the Solution properties for CometUI.

**Comment by wfondrie** [comment]
Do you know how to do this either in the code or from the command line? I'm on a Mac. 

Like @mammmals mentioned, it seems like changing the following to `false` would accomplish this: https://github.com/UWPR/Comet/blob/e08d3e7c0dcffc32f2e117c13b4cd1b47141178b/CometUI/CometUI.csproj#L80

**Comment by mhoopmann** [comment]
Sorry, no.

**Comment by jke000** [comment]
@wfondrie, instead of building the entire solution, are you able to just build individual projects?  If so, simply build the Comet project to get Comet.exe.  If not, I can explore ClickOnce certificates more to see if it can be generated without the password.

**Comment by wfondrie** [comment]
It wouldn't be a problem to only build Comet.exe. However, I was able to make the change above---disabling `SignManifests`--- and now everything works. What do you think is the better solution?

**Comment by jke000** [comment]
If it's working now, leave as-is.  Thanks!

**Review by mammmals — APPROVED** [review]
Looks good, we can do Compress-Archive if needed as well for the zip.
There's GH specific release actions as well, but now that we've got it working let's get it to the main repo.

**Comment by wfondrie** [comment]
Yeah hopefully those release actions work as expected 🤞. 

Unfortunately I don't know of a great way to test them, aside from creating a new release and seeing if it works. The good news is that I have used similar actions before, so I'm fairly sure these will work.

**Comment by mammmals** [comment]
Looks like the upload release assets isn't working for some reason.

**Comment by mammmals** [comment]
Very exciting, first run failed for a tag issue, but latest test worked like a charm! @wfondrie could you test on a mac/linux?

**Comment by wfondrie** [comment]
I just tried the MacOS and Linux versions and they seem to work 👍

**Pull request merged**
