### PR TITLE
Add GitHub Actions for Releases and a Docker container

### PR DESCRIPTION
**Pull request by wfondrie**
This PR refactors our previous GitHub Actions workflows to automatically upload build artifacts to releases created within GitHub. Here's how it should work:

When a commit is pushed to `master` or a pull-request is made with `master` as the target of the merge:

1. Comet will be compiled on Ubuntu, MacOS, and Windows.
2. We check that the new Comet executable can create a new param file. *(Here is an excellent place for other tests if we have them)*
3. If any build / test fails, we should see an ❌ notifying us. If it's a pull-request we should probably fix the problem before merging it into `master` 😉.
4. For the Linux build, we create a Docker container and verify that the Docker container works (per #5).

When a new release is created using the "Releases" tab in GitHub:
1. Comet will be compiled on Ubuntu, MacOS, and Windows.
2. We check that the new Comet executable can create a new param file. *Hopefully neither of these steps fail, because they should have completed successfully when the most recent commit was added to `master`.*
3. Each build will upload it's build artifacts to the Release page. Currently, I've configured these to be a compressed archive containing the executable and `README.md` for each platform. After all have completed you should see `linux.tar.gz`, `macos.zip`, and `windows.zip` available for download under the Releases tab.
4. For the LInux build, we create a Docker container. This is uploaded to the [GitHub Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/) where folks can use Docker to grab it.

I'd advise on waiting to merge this PR until we have the Windows build up and running.

Any other feature requests, questions, or comments?

### CODE REVIEW

**Comment by jke000** [comment]
Here's a couple of basic questions.  I have been adding release notes with
each release.  I'm just trying to understand where the release notes should
exist as the root README.md doesn't seem to be the right place for the
release notes.  Presumably add some file like RELEASENOTES.txt to the repo
and copy that to each release archive?

I have a set of tests I've been running before each release.  It's
currently a manual process to edit each of the parameters for the various
tests for each new release as I'm effectively running a bunch of searches
and validating the results.  What's the proper way to adding such tests and
I guess specifically any advice on how I should deal with the spectra and
sequences?  Encode those within the program itself (not too horrible for
the small tests) or can the data be external from the binary itself?

**Comment by wfondrie** [comment]
> Presumably add some file like RELEASENOTES.txt to the repo and copy that to each release archive?

This seems like a good idea to me. In my Python projects I use a file called `CHANGELOG.md` that contains the release history in the format suggested by https://keepachangelog.com/en/1.0.0/. 

Regardless, we can put any files you want into the release archives.

> What's the proper way to adding such tests and I guess specifically any advice on how I should deal with the spectra and sequences?  Encode those within the program itself (not too horrible for the small tests) or can the data be external from the binary itself?

I'm certainly not an expert on testing C++ programs, but I know that the crux folks use [Cucumber](https://cucumber.io/) to run such tests (in crux they call these "smoke tests", but I think a lot of folks would call them "system tests". Alternatively I use [pytest](https://docs.pytest.org) to run unit and system tests on all of my Python packages. If we just want to run Comet with different sets of parameters and compare the outputs, I could do this fairly easily with some Python code. Lastly, if we ever want to write unit tests (testing specific functionality within the code base), then [GoogleTest](https://google.github.io/googletest/) is probably the most popular option (and the Percolator folks have started using it too).

As for where the tests go, they certainly do not have to be included with the executable. I think we would want to create a top level `tests` directory where the testing code, spectra, and sequences could reside. Additionally, if the spectra and/or sequences are too large to reasonably store in version control, we could also download them from somewhere before the tests are run.

In the case of crux, I know they keep small spectra and sequence files in the GitHub repo for testing.

**Review by mammmals — COMMENTED** [review]
Looks good overall with the windows build holding us up for now.

**Review by mammmals — APPROVED** [review]
Approving to move forward

**Pull request merged**
